import type { Metadata } from "next";
import { Anek_Devanagari } from "next/font/google";
import { Analytics } from "@vercel/analytics/react";
import "./globals.css";

const Anek = Anek_Devanagari({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={Anek.className}>
        {children}
        <Analytics />
      </body>
    </html>
  );
}
